1. numpy 基本操作

In [2]:
import numpy as np
array = np.array([
    [1, 3, 5],
    [4, 6, 9]
])
print(type(array))
print(array)

<class 'numpy.ndarray'>
[[1 3 5]
 [4 6 9]]


In [3]:
array.ndim

2

In [4]:
array.shape

(2, 3)

In [6]:
array.size

6

2.numpy创建array

In [8]:
a = np.array([2, 23, 4], dtype=np.int32)
print(a)
print(type(a))
print(a.dtype)

[ 2 23  4]
<class 'numpy.ndarray'>
int32


In [9]:
a = np.array([[2, 3, 4], [3, 4, 5]])
print(a)

[[2 3 4]
 [3 4 5]]


In [11]:
a = np.zeros((3, 4))
print(a)
b = np.zeros(5)
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0. 0. 0. 0. 0.]


In [12]:
a = np.ones((3, 4), dtype=np.int)
print(a)
print(a.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int64


In [13]:
a = np.empty((3, 4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
a = np.arange(10, 21, 2)
print(a)

[10 12 14 16 18 20]


In [15]:
b = a.reshape(2, 3)
b

array([[10, 12, 14],
       [16, 18, 20]])

In [16]:
a = np.linspace(1, 10, 20)
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [17]:
b = a.reshape((5, 4))
print(b)

[[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]


3.numpy基本运算

In [18]:
a = np.array([10, 20, 30, 40])
b = np.arange(4)
c = a - b
print(c)

[10 19 28 37]


In [19]:
a * b

array([  0,  20,  60, 120])

In [20]:
a.dot(b)

200

In [21]:
b**2

array([0, 1, 4, 9])

In [22]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

In [23]:
b < 2

array([ True,  True, False, False])

In [24]:
a = np.array([1, 1, 4, 3])
b = np.arange(4)
print(a==b)

[False  True False  True]


In [27]:
#多维
a = np.array([[1, 1], [0, 1]])
b = np.arange(4).reshape(2, 2)
print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


In [28]:
a.dot(b)

array([[2, 4],
       [2, 3]])

In [29]:
np.dot(a, b)

array([[2, 4],
       [2, 3]])

In [30]:
a * b

array([[0, 1],
       [0, 3]])

In [31]:
a = np.random.random((2, 4))
print(a)
print(np.sum(a))
print(np.min(a))
print(np.max(a))

[[0.34693748 0.02181092 0.04901364 0.17059944]
 [0.27038805 0.68456222 0.75553266 0.81897739]]
3.117821788774107
0.021810920394580102
0.8189773858023651


In [32]:
print(np.sum(a, axis=1))
print(np.max(a, axis=1))
print(np.min(a, axis=1))

[0.58836147 2.52946032]
[0.34693748 0.81897739]
[0.02181092 0.27038805]


In [33]:
print(np.sum(a, axis=0))
print(np.max(a, axis=0))
print(np.min(a, axis=0))
# 当axis的值为0的时候，将会以列作为查找单元，
# 当axis的值为1的时候，将会以行作为查找单元。

[0.61732552 0.70637314 0.8045463  0.98957682]
[0.34693748 0.68456222 0.75553266 0.81897739]
[0.27038805 0.02181092 0.04901364 0.17059944]


In [35]:
A = np.arange(2, 14).reshape(3, 4)
A

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [36]:
A = np.arange(2, 14).reshape((3, 4))
A

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [37]:
print(np.argmin(A))
print(np.argmax(A))

0
11


In [38]:
print(np.mean(A))
print(np.average(A))
print(A.mean())
print(np.median(A))
print(np.cumsum(A))

7.5
7.5
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [40]:
B = np.array([[3, 5, 9], [4, 8, 10]])
B

array([[ 3,  5,  9],
       [ 4,  8, 10]])

In [41]:
np.diff(B)

array([[2, 4],
       [4, 2]])

In [42]:
C = np.array([[0, 5, 9], [4, 0, 10]])
print(np.nonzero(B))
print(np.nonzero(C))

(array([0, 0, 0, 1, 1, 1]), array([0, 1, 2, 0, 1, 2]))
(array([0, 0, 1, 1]), array([1, 2, 0, 2]))


In [43]:
A = np.arange(14, 2, -1).reshape(3, 4)
A

array([[14, 13, 12, 11],
       [10,  9,  8,  7],
       [ 6,  5,  4,  3]])

In [44]:
print(np.sort(A))

[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [45]:
print(np.transpose(A))

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [46]:
print(A.T)

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


In [47]:
print(np.clip(A, 5, 9))

[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


4 索引和切片

In [48]:
A = np.arange(3, 15)
print(A[3])
B = A.reshape(3, 4)
print(B[2])
print(B[0][2])
print(B[0, 2])

6
[11 12 13 14]
5
5


In [49]:
print(B)
print(B[1, 1:3])

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[8 9]


In [50]:
for row in B:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [51]:
for c in B.T:
    print(c)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [52]:
A = np.arange(3, 15).reshape(3, 4)
print(A)
print(A.flatten())
for item in A.flat:
    print(item)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14


5.numpy array 合并

In [55]:
A = np.array([1, 1, 1])
B = np.array([2, 2, 2])
print(np.vstack((A, B)))

[[1 1 1]
 [2 2 2]]


In [56]:
C = np.vstack((A, B))
print(C)
print(A.shape, B.shape, C.shape)

[[1 1 1]
 [2 2 2]]
(3,) (3,) (2, 3)


In [57]:
D = np.hstack((A, B))
print(D)
print(A.shape, B.shape, D.shape)

[1 1 1 2 2 2]
(3,) (3,) (6,)


In [58]:
print(A[np.newaxis, :])
print(A[np.newaxis, :].shape)
print(A[:, np.newaxis])

[[1 1 1]]
(1, 3)
[[1]
 [1]
 [1]]


In [60]:
print(A)
print(B)
A = A[:, np.newaxis]
B = B[:, np.newaxis]
print(A)
print(B)

[1 1 1]
[2 2 2]
[[1]
 [1]
 [1]]
[[2]
 [2]
 [2]]


In [62]:
C = np.concatenate((A,B,B,A), axis=0)
print(C)
C = np.concatenate((A, B), axis=1)
print(C)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
[[1 2]
 [1 2]
 [1 2]]


In [63]:
a = np.arange(8).reshape(2, 4)
b = np.arange(8).reshape(2, 4)
print(a)
print(b)

[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]


In [64]:
c = np.concatenate((a, b), axis=0)
print(c)
c = np.concatenate((a, b), axis=1)
print(c)

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3 0 1 2 3]
 [4 5 6 7 4 5 6 7]]


6.numpy array 分割

In [65]:
A = np.arange(12).reshape(3, 4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [66]:
print(np.split(A, 2, axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


In [67]:
print(np.split(A, 3, axis=0))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [68]:
print(np.array_split(A, 3, axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [69]:
print(np.vsplit(A, 3))
print(np.hsplit(A, 2))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


7.Numpy copy 与==

In [70]:
a = np.arange(4)
print(a)

b = a
c = a
d = b
a[0] = 11
print(a)
print(b)
print(c)
print(d)

[0 1 2 3]
[11  1  2  3]
[11  1  2  3]
[11  1  2  3]
[11  1  2  3]


In [71]:
print(b is a)
print(c is a)
print(d is a)

True
True
True


In [72]:
d[1:3] = [22, 33]
print(a)
print(b)
print(c)

[11 22 33  3]
[11 22 33  3]
[11 22 33  3]


In [73]:
a = np.arange(4)
print(a)
b = a.copy()
print(b)
a[3] = 44
print(a)
print(b)

[0 1 2 3]
[0 1 2 3]
[ 0  1  2 44]
[0 1 2 3]


8.广播机制

In [75]:
a = np.array([[0, 0, 0], [10, 10, 10], [20, 20, 20], [30, 30, 30]])
b = np.array([0, 1, 2])
print(a + b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [76]:
b = np.tile([0, 1, 2], (4, 1))
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [77]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

9.常用函数

In [78]:
x = np.array([1, 2, 3, 3, 0, 1, 4])
np.bincount(x)

array([1, 2, 1, 2, 1])

In [79]:
w = np.array([0.3, 0.5, 0.7, 0.6, 0.1, -0.9, 1])
np.bincount(x, weights=w)

array([ 0.1, -0.6,  0.5,  1.3,  1. ])

In [80]:
x = [[1, 3, 3], [7, 5, 2]]
np.argmax(x)

3

In [81]:
np.argmax(x, axis=0)

array([1, 1, 0])

In [82]:
np.argmax(x, axis=1)

array([1, 0])

In [83]:
x = np.array([1, 3, 2, 3, 0, 1, 0])
print(x.argmax())

1


In [84]:
x = np.array([1, 2, 3, 3, 0, 1, 4])
print(np.argmax(np.bincount(x)))

1


In [85]:
np.around([-0.6, 1.2798, 2.357, 9.67, 13], decimals=0)

array([-1.,  1.,  2., 10., 13.])

In [86]:
np.around([1.2798, 2.357, 9.67, 13], decimals=1)

array([ 1.3,  2.4,  9.7, 13. ])

In [87]:
np.around([1.2798, 2.357, 9.67, 13], decimals=2)

array([ 1.28,  2.36,  9.67, 13.  ])

In [88]:
np.around([1, 2, 5, 6, 56], decimals=-1)

array([ 0,  0,  0, 10, 60])

In [89]:
np.around([1, 2, 50, 56, 190], decimals=-2)

array([  0,   0,   0, 100, 200])

In [90]:
x = np.arange(1, 16).reshape(3, 5)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [91]:
np.diff(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [92]:
np.diff(x, axis=0)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [93]:
np.floor([-0.6, -1.4, -0.1, -1.8, 0, 1.4, 1.7])

array([-1., -2., -1., -2.,  0.,  1.,  1.])

In [94]:
np.ceil([1.2, 1.5, 1.8, 2.1, 2.0, -0.5, -0.6, -0.3])

array([ 2.,  2.,  2.,  3.,  2., -0., -0., -0.])

In [95]:
x = np.array([[1, 0], [2, -2], [-2, 1]])

In [96]:
x

array([[ 1,  0],
       [ 2, -2],
       [-2,  1]])

In [97]:
np.where(x>0,x,0)

array([[1, 0],
       [2, 0],
       [0, 1]])